# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required

cache: packages

bioc_packages:
- BiocStyle
- biomaRt
- ComplexHeatmap
- limma
- MSstats
- org.Ag.eg.db
- org.At.tair.db
- org.Bt.eg.db
- org.Ce.eg.db
- org.Cf.eg.db
- org.Dm.eg.db
- org.Dr.eg.db
- org.EcK12.eg.db
- org.EcSakai.eg.db
- org.Gg.eg.db
- org.Hs.eg.db
- org.Mm.eg.db
- org.Mmu.eg.db
- org.Pf.plasmo.db
- org.Pt.eg.db
- org.Rn.eg.db
- org.Ss.eg.db
- org.Xl.eg.db

r_check_args: --no-build-vignettes --no-vignettes

warnings_are_errors: false

after_success:
  - Rscript -e 'library(covr); codecov()'